// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ltffQxl6i3XdmaqHXyJpvg8SM3h9h7o',
    appId: '1:233817841525:web:5255d6e2caa469dbb2fd3c',
    messagingSenderId: '233817841525',
    projectId: 'the-boos-163d6',
    authDomain: 'the-boos-163d6.firebaseapp.com',
    storageBucket: 'the-boos-163d6.firebasestorage.app',
    measurementId: 'G-Z7CZ6FD7JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZBlYlSFcvUbhrYKzprVF9A4GK2P0Apbs',
    appId: '1:233817841525:android:970dca87cfd8d479b2fd3c',
    messagingSenderId: '233817841525',
    projectId: 'the-boos-163d6',
    storageBucket: 'the-boos-163d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnmZZoNY5IXpj72sWw__jfXLjji4ckMAw',
    appId: '1:233817841525:ios:7e84737d0c680498b2fd3c',
    messagingSenderId: '233817841525',
    projectId: 'the-boos-163d6',
    storageBucket: 'the-boos-163d6.firebasestorage.app',
    iosBundleId: 'com.example.thisBooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnmZZoNY5IXpj72sWw__jfXLjji4ckMAw',
    appId: '1:233817841525:ios:7e84737d0c680498b2fd3c',
    messagingSenderId: '233817841525',
    projectId: 'the-boos-163d6',
    storageBucket: 'the-boos-163d6.firebasestorage.app',
    iosBundleId: 'com.example.thisBooks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9ltffQxl6i3XdmaqHXyJpvg8SM3h9h7o',
    appId: '1:233817841525:web:fa5f9a8fe02194e6b2fd3c',
    messagingSenderId: '233817841525',
    projectId: 'the-boos-163d6',
    authDomain: 'the-boos-163d6.firebaseapp.com',
    storageBucket: 'the-boos-163d6.firebasestorage.app',
    measurementId: 'G-17VMS5EB04',
  );
}
